### ISSUE TITLE
rolling 2 dice types

### ISSUE THREAD

**Issue by OdedDeutch** [arkie/hackyslack2#10]
One can roll 2d4+1 correctly but the  3d4+3d6 will interpreted as (3d4+3)+(1d6)

**Comment by arkie** [comment]
`/roll 3d4 3d6` will do what you want. The primary issue here is that it's parsed left to right (via regex).

Feel free to reopen if would prefer syntax altered.

**Comment by arkie** [comment]
Actually fixed in last commit.

<img width="393" alt="screen shot 2016-09-03 at 21 12 45" src="https://cloud.githubusercontent.com/assets/232986/18229003/3305b92a-721b-11e6-8509-b2f0b9c14a14.png">
