### ISSUE TITLE
[Feature Request] ignore spaces in the line altogether

### ISSUE THREAD

**Issue by Granite26** [arkie/hackyslack2#11]
3d3-10 works but 3d3 - 10 doesn't :/

**Comment by arkie** [comment]
It doesn't strip spaces, but it should allow additional whitespace around the arithmetic operators now.
<img width="392" alt="screen shot 2016-09-03 at 21 02 06" src="https://cloud.githubusercontent.com/assets/232986/18228973/c575dc4c-7219-11e6-80c6-84b4c747339f.png">
