### ISSUE TITLE
Savage Worlds exploding dice +wild die

### ISSUE THREAD

**Issue by kurtpotts** [arkie/hackyslack2#12]
Is it possible to have dice explode (if the result is the highest number on the die roll it again and add them together)? right now when you type explode it adds a d6 which doesn't explode and adds it to your total. 

I would also like to see an option to roll two dice, 1d8 and 1d6 for example, and take the higher result for the Savage Worlds wild die mechanic.

**Comment by arkie** [comment]
<img width="422" alt="screen shot 2016-09-03 at 23 10 04" src="https://cloud.githubusercontent.com/assets/232986/18229370/e9cb43d6-722b-11e6-9639-a22c017fd3a0.png">
