### ISSUE TITLE
Add Support for Modifiers

### ISSUE THREAD

**Issue by adanvdo** [arkie/hackyslack2#20]
This slack app is pretty sweet, but it would be even sweeter if you could specify a modifier to be added to the roll.  I added this to a D&D team that I started and the modifier would make it perfect for playing out scenarios.

Example: /roll 1d20+3 would get the random roll for a 20-sided die and add 3 to it.

**Comment by arkie** [comment]
I'm not sure I follow - that should be working? Closing out pending an example roll you can give where it isn't being processed with the modifier?

<img width="427" alt="screen shot 2017-03-17 at 22 55 48" src="https://cloud.githubusercontent.com/assets/232986/24069410/fe1cda5c-0b64-11e7-8b40-d989966a967a.png">

**Comment by adanvdo** [comment]
That is completely my fault. I didn't try it. I just assumed it wasn't
supported because I didn't see it in the documentation. Thank you!

**Comment by arkie** [comment]
Hehe, there are a whole bunch of requested features not documented in the documentation (pull requests accepted 😉)
