### ISSUE TITLE
Add support for Fate Dice

### ISSUE THREAD

**Issue by piersb** [arkie/hackyslack2#22]
/roll dFate - roll four fate dice
/roll dfate, /roll dFate, /roll df, /roll dF - alternate calls for above

/roll XdFate - roll X fate dice
/roll Xdfate, /roll XdFate, /roll Xdf, /roll XdF - alternate calls for above

**Comment by piersb** [comment]
Mostly duplicates #9, only difference is the alternate calls

**Comment by arkie** [comment]
All of the second syntaxes should work as of https://github.com/arkie/hackyslack2/pull/23 (and the non-capitalized versions should have already worked) but based on https://en.wikipedia.org/wiki/Fudge_(role-playing_game_system)#Fudge_dice currently keeping the default to one die (mostly for consistency with the [dice notation](https://en.wikipedia.org/wiki/Dice_notation) describing the default as one die).
