### ISSUE TITLE
Give values other than numbers

### ISSUE THREAD

**Issue by dmwelch** [arkie/hackyslack2#25]
E.g. bingo:

`/roll 1dBINGO 1d99`

returns

> Dice | Rolls
> 1dBINGO        | G
> Dice               | Rolls
> 1d99              | 35

**Comment by arkie** [comment]
I think this move overlap a bit too much with non-digit parsing (i.e. `df` or `d%`) to be able to be added cleanly, as well as be a unique enough syntax to be more likely an error (e.g. from the attempts in https://github.com/arkie/hackyslack2/issues/22) than intentionally used with expectation of working this way.
