### ISSUE TITLE
Dice rolling in slack threads

### ISSUE THREAD

**Issue by berzerkergamer** [arkie/hackyslack2#26]
I hope this is the right place to make requests. Me and my friends use the dice rolling app in slack for a D&D game we are playing and it is a great app. It would be extremely helpful to be able to use the dice rolling app in the slack threads you can start when someone posts something. Currently you can only use /roll in the main chat channel. Is this possible? Sorry to bother you about it but I don't know the first thing about coding.

**Comment by arkie** [comment]
As best I can tell from https://api.slack.com/slash-commands and other non-first-party commands (e.g. `/giphy`) this isn't currently an option. Happy to add if that changes 👍

**Comment by berzerkergamer** [comment]
I found these webpages that seem to say that slack now supports apps in threads? It seems to give instructions on how to program an app to take commands from a thread? Again I know very little about coding so I possibly don't know what I'm talking about 😋.

https://api.slack.com/docs/message-threading

https://medium.com/slack-developer-blog/bringing-your-bot-into-threaded-messages-cd272a42924f

**Comment by arkie** [comment]
The main issue is that those are for full bot integrations, which require `permission to read and write messages` while the dicebot only asks for permission to `add commands` (and thus doesn't need to be explicitly invited into channels, or have the ability to read messages not prefixed with `/roll`)

Something like [Hubot](https://hubot.github.com/) has that ability (note thread support request https://github.com/slackapi/hubot-slack/issues/393) but not the simpler command API being used, I believe.

**Comment by berzerkergamer** [comment]
Ok I understand now. Thanks for your time.
