### ISSUE TITLE
Would you accept some documentation?

### ISSUE THREAD

**Issue by tabatkins** [arkie/hackyslack2#27]
Heya, I've been using dicebot for a while and loving it, but I've been forced to gradually discover the functionality from usage, as there is effectively no documentation for the project. I write specs for a living, and would be happy to write up some docs for the syntaxes - would you accept a PR to your README?

**Comment by arkie** [comment]
Sure - would likely make sense to have a README.md in https://github.com/arkie/hackyslack2/tree/master/dicebot/roll although having a bit more info on https://dice-b.appspot.com would probably also make sense 😄

**Comment by tabatkins** [comment]
Dunno where the appspot text is generated from, but I'd be happy to write for that as well, or you can extract from my PR in a bit.

**Comment by arkie** [comment]
https://github.com/arkie/hackyslack2/blob/master/dicebot/template/index.html#L23 Generated is a strong word (and sounds good)

**Comment by tabatkins** [comment]
Forgot to link the PR (#28) with this issue in the commit message, but obviously we can close this once it merges. ^_^

**Comment by arkie** [comment]
Awesome, thanks!
