### ISSUE TITLE
parsing words with number

### ISSUE THREAD

**Issue by whbdupree** [arkie/hackyslack2#29]
Is this intentional behavior? Here, I have not written 'for test1' by omitting the 'for'.
/roll d6+6 test1
and dicebot gives me
@xxxx rolled *6* + *6* + *1* = *13*

Dicebot has parsed the string 'test1' and interpreted it as intent to add 1.

**Comment by arkie** [comment]
The parser is fairly lax, but I'd consider this more undefined behavior rather than intentional. It doesn't default to the `for` style labelling since that would result in it possibly missing additional rolls or modifications.
