### ISSUE TITLE
Dicebot is bad at Math

### ISSUE THREAD

**Issue by Krule** [arkie/hackyslack2#30]
> /roll 1d1 + 4 * 10
>
> rolled 1 + 4 × 10 = 50

**Comment by arkie** [comment]
<img width="273" alt="screen shot 2017-11-22 at 09 52 09" src="https://user-images.githubusercontent.com/232986/33142319-de6e2f92-cf6a-11e7-87c6-cc2586c15099.png">

Dicebot is fine at math, it just evaluates left to right to avoid the need for parentheses in the syntax 👍
