### ISSUE TITLE
Can this dice bot support multiplication

### ISSUE THREAD

**Issue by RavenTheDarkLoad** [arkie/hackyslack2#6]
like 3d6x3 or 3d6*3
sum rolls result [3,2,5]  = 10
than [10 times 3] = 30

**Comment by arkie** [comment]
How would you expect this to interact with the other modifiers (e.g. + / - / > / k)?

**Comment by arkie** [comment]
This should now work with constants, and dice.

<img width="390" alt="screen shot 2016-09-03 at 21 05 20" src="https://cloud.githubusercontent.com/assets/232986/18228981/32ebc23c-721a-11e6-871c-a3a20c2b2a73.png">
