### ISSUE TITLE
Support the 4dF syntax used by Fate and Fudge

### ISSUE THREAD

**Issue by amazingrando** [arkie/hackyslack2#9]
https://en.wikipedia.org/wiki/Fudge_(role-playing_game_system)#Game_mechanics

This would make it much easier to run Fate games using a Slack channel so I would appreciate it if you would consider this feature. Thanks!

**Comment by Granite26** [comment]
A quick and dirty way to do this is Xd3-2X

You'll have to do the 2X multiplication yourself, though :)

**Comment by mertenhanisch** [comment]
it would still be cool to have 4dF :)
+1

**Comment by arkie** [comment]
<img width="406" alt="screen shot 2016-09-03 at 23 14 35" src="https://cloud.githubusercontent.com/assets/232986/18229378/344991ec-722c-11e6-8611-9a48e132a605.png">

**Comment by amazingrando** [comment]
@arkie Thanks for adding Fate Dice!
